o_fort_core:
    resource: "@OFortCoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

o_fort_prerentree:
    resource: "@OFortPrerentreeBundle/Resources/config/routing.yml"
    prefix:   /prerentree

prerentree:
    resource: "@PrerentreeBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform


