o_fort_prerentree_homepage:
    path:     /
    defaults: { _controller: OFortPrerentreeBundle:Default:index }

o_fort_prerentree_structure:
    path:     /structure
    defaults:
        _controller: OFortPrerentreeBundle:Structures:index

o_fort_prerentree_struct_add:
    path:     /structure/add
    defaults:
        _controller: OFortPrerentreeBundle:Structures:add

o_fort_prerentree_struct_modify:
    path:     /structure/modify/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Structures:modify

o_fort_prerentree_struct:
    path:     /structure/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Structures:view

o_fort_prerentree_struct_del:
    path:     /structure/del/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Structures:del

o_fort_prerentree_struct_confirmdel:
    path:     /structure/confirmdel/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Structures:confirmDel

o_fort_prerentree_enseignement_add:
    path:   /enseignement/add/{idMaquette}
    defaults:
        _controller: OFortPrerentreeBundle:Enseignement:add

o_fort_prerentree_enseignement_view:
    path:  /enseignement/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Enseignement:view

o_fort_prerentree_enseignement_modify:
    path:  /enseignement/modify/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Enseignement:modify

o_fort_prerentree_repartition_add:
    path: /repartition/add/{assoId}
    defaults:
        _controller: OFortPrerentreeBundle:Repartition:add

o_fort_prerentree_repartition_addBarette:
    path: /repartition/addBarette/{baretteId}
    defaults:
        _controller: OFortPrerentreeBundle:Repartition:addForBarette

o_fort_prerentree_repartition_delete:
    path: /repartition/delete/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Repartition:delete

o_fort_prerentree_repartition_confirmDelete:
    path: /repartition/confirmdelete/{id}
    defaults:
        _controller: OFortPrerentreeBundle:Repartition:confirmDelete

o_fort_prerentree_discipline:
    resource: "@OFortPrerentreeBundle/Resources/config/discipline/routing.yml"
    prefix:   /discipline

o_fort_prerentree_maquette:
    resource: "@OFortPrerentreeBundle/Resources/config/maquette/routing.yml"
    prefix:   /maquette

o_fort_prerentree_enseignement:
    resource: "@OFortPrerentreeBundle/Resources/config/enseignement/routing.yml"
    prefix:   /enseignement

o_fort_prerentree_division:
    resource: "@OFortPrerentreeBundle/Resources/config/division/routing.yml"
    prefix:   /division

o_fort_prerentree_niveau:
    resource: "@OFortPrerentreeBundle/Resources/config/niveau/routing.yml"
    prefix:   /niveau

o_fort_prerentree_barette:
    resource: "@OFortPrerentreeBundle/Resources/config/barette/routing.yml"
    prefix:   /barette

o_fort_prerentree_niveauFormation:
    resource: "@OFortPrerentreeBundle/Resources/config/niveauFormation/routing.yml"
    prefix:   /niveauFormation

o_fort_prerentree_filiere:
    resource: "@OFortPrerentreeBundle/Resources/config/filiere/routing.yml"
    prefix:   /filiere