<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * associationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class associationRepository extends \Doctrine\ORM\EntityRepository
{
}
