<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * BaretteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class baretteRepository extends \Doctrine\ORM\EntityRepository
{
}
