<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * disciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class disciplineRepository extends \Doctrine\ORM\EntityRepository
{
}
