<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * divisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class divisionRepository extends \Doctrine\ORM\EntityRepository
{
}
