<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * enseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enseignementRepository extends \Doctrine\ORM\EntityRepository
{
}
