<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * filiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filiereRepository extends \Doctrine\ORM\EntityRepository
{
}
