<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * maquetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class maquetteRepository extends \Doctrine\ORM\EntityRepository
{
}
