<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * niveauFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class niveauFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
