<?php

namespace OFort\PrerentreeBundle\Repository;

/**
 * structureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class structureRepository extends \Doctrine\ORM\EntityRepository
{
}
